### PR TITLE
Upgrades + Remove jQuery

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
depends on:https://github.com/emberjs/data/pull/5386

### CODE REVIEW

**Comment by elwayman02** [comment]
It's not an issue for me, but I'll leave that up to @Dhaulagiri

**Comment by Dhaulagiri** [comment]
@NullVoxPopuli were you still thinking of trying to land this change?

**Comment by NullVoxPopuli** [comment]
Not actively. If you want to give it a go, go for it

**Comment by NullVoxPopuli** [comment]
Cleaning up my PRs (the list at https://github.com/pulls). If this effort is still useful, feel free to cherry-pick.

**Pull request closed without merging**
