### PR TITLE
Adding support for pull requests

### LINKED ISSUE #19: Add support for listing pull requests from a repo
Would like to list PR's in public and private repos, either directly

```js
this.get('store').findRecord('githubPullrequests', 'username/reponame'); // get a list of PR's
```

or after a repo request.

```js
let repo = this.get('store').findRecord('githubRepository', 'jimmay5469/old-hash');
repo.githubRepositories
```

Would be happy to provide a PR for this if you can provide some detail on how you want it implemented?

Thanks.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/33862277-add-support-for-listing-pull-requests-from-a-repo?utm_campaign=plugin&utm_content=tracker%2F15732968&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F15732968&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by catchamonkey**
Closes #19 

So far this works as I expect, but would appreciate some feedback.

Thanks!

### CODE REVIEW

**Comment by elwayman02** [comment]
@catchamonkey thanks for this! I'll take a look now. Seems like the build is failing a few tests, can you check it out?

**Comment by elwayman02** [comment]
Also, it would be great if you could add something to the dummy app, perhaps?

**Comment by catchamonkey** [comment]
Thanks @elwayman02 I'll get the tests updated first, then will dig into the dummy app.

**Comment by catchamonkey** [comment]
@elwayman02 the dummy app doesn't appear to have anything in it at all, there is no list of repos or anything, so can't make an amendment to get PRs out too really. I'll get the test fixed though.

**Pull request merged**
